### ISSUE TITLE
[P2] test_stage_b_tail_1187 fails on main: its stand-in emitter has no capture_batch since #1194

### ISSUE THREAD

**Issue by RobTand** [RobTand/prismaquant#1202]
**Severity: P2.** Main's CI is red on one test, which hides new failures in that shard. The defect is in the test's fixture, not the product code.

## What fails

`tests/test_stage_b_tail_1187.py::test_a_band_serial_handoff_is_written_under_its_own_span` fails on main with:

```
prismaquant/joint_cost_quantum.py:1519: AttributeError: 'types.SimpleNamespace' object has no attribute 'capture_batch'
```

Since #1194, `run_layer_quantum_core` compares the emitter's `capture_batch` with the launch's replay regime. The test's stand-in emitter is a `SimpleNamespace(emit=..., published={})` with no `capture_batch`.

## Receipts

- Fails on main: PB `fe8c4736ebc7` (sparky), `e9106320e9c7`. It is also red in main's CI (run 36041661042).
- Found independently by WS-CHAIN2 (#1163) and WS-PIPE2 (#1192): shard 3 of #1163's green run (`c4f98a7da604`) and the first green run of #1192 fail only on this test.

## Fix

The stub carries the launch regime's capture batch, as `HandoffEmitter` does.
