### PR TITLE
Refuse incomplete MoE campaigns and capture explicit packed expert inputs

### PR DESCRIPTION
**Pull request by RobTand**
Related to #183; this deliberately does not close it.

The campaign now refuses a live packed-expert population before it can emit an incomplete dense-only cost payload. The capture helper can independently collect each profile-declared expert projection's actual routed inputs and full-row Hessian, reusing the existing packed collector, routing/SwiGLU implementation, and native projection views. Scoring-row limits never truncate the Hessian; unobserved selected experts refuse.

The main packed-population gate remains closed. Exact producer source-to-stack planning, identity-bound cached-blob packing, and an actual matched-byte served campaign are separate remaining work. No new menu, pin roster, encoder default, serving eligibility, or GPU/performance claim is introduced.

Separate on-path commits:

- Honor the profile's existing BF16 pins in dense campaign target enumeration.
- Correct stale architecture resume-identity prose and an obsolete rule-number citation.
- Exercise both FP32 and BF16 live capture inputs.

Based on main `10dd23957d6cf9ad784f8eac59fb914f66f6d89e`, after PR #185; no duplicate endpoint dependency commits are included. Historical red/green actions, commands, populations, and receipts are in `docs/measurements/tessera-packed-capture-2026-09-04.md`.

CPU evidence through deployed PrismaBuild, Sparky / 1 CPU / 4 GiB / no CUDA:

- Genuine pre-fix main omissions: 2 failures; packed capture: 4 failures; pin intake: 2 failures.
- Capture + existing reservoir/campaign/streaming files: 41 passed, 7 skips (5 `Tessera encodes need CUDA`, 2 `streaming production render is GPU-or-bust`). Streaming equivalence was not exercised.
- Shared discovery/router/docs: 41 passed, no skips.
- Pins + campaign regression: 39 passed, 5 `Tessera encodes need CUDA` skips.
- FP32/BF16 capture + pins/docs: 28 passed, no skips; both dtype cases also failed against the exact pre-capture campaign implementation.

The combined targeted population on the updated integration base is queued as PrismaBuild `8c87b0777dae`; its result will be added before merge. These overlapping historical populations must not be summed into a suite count.

Encountered checkpoint-resume identity defect is separately filed and actively assigned as #186. It is not hidden in this capture diff.

### CODE REVIEW

**Comment by RobTand** [comment]
Combined targeted result on the updated integration base is GREEN: PrismaBuild 8c87b0777daeda083396c2e5a16f474089125ab860c06701eb0f9c83d5892674, 79 passed / 7 skipped / no uncollected module reported. CPU-only serial Sparky, 1 CPU / 4 GiB. Skip reasons verbatim: 5 × Tessera encodes need CUDA; 2 × streaming production render is GPU-or-bust. Receipt 4ae92d4004626ce1b9015300bb40a62cabc08cf1a2b3828de9b1e3076ea93585. Evidence appended to docs/measurements/tessera-packed-capture-2026-09-04.md. No packed campaign/export gate was opened; #183 remains open.

**Comment by RobTand** [comment]
## Brought up to date with `main` (PR #196) and verified — worker `pq-campaign`

**Tip:** `0b01bc62` · `gh pr view 187 --json mergeable` → `MERGEABLE` (branch merged with `origin/main` by merge commits; no authored commit rewritten). CI on the previous tip `e3a2f323` (same code, before the two doc-only re-merges below) was green.

*Updated:* `origin/main` moved twice while this was in review; `679c03c6` merges main at `5ab603e6` (PRs #188, #189) and `0b01bc62` merges main at `65cfa6d9` (PR #190). Both conflicted only in the `docs/ARCHITECTURE.md` header (resolved: As-of names this branch + 2026-09-05, every stamp from both sides kept newest first, this branch's above main's); `tests/test_tessera_scope_endpoints.py` auto-merged. The test set below was re-run on `0b01bc62` at the pin: **298 passed, 7 skipped, 0 failed** (`tests/test_cost_currency.py` added to the set because #188's `_tessera_rows` currency refusal touches campaign cost tables; the campaign payload stamps `CURRENCY` and passes).

### Merge resolution — `18715ede` (Merge origin/main (PR #196) into codex/pq183-packed-capture)

Conflicts: three hunks in `prismaquant/tessera_campaign.py`, one in `docs/ARCHITECTURE.md`. Resolved on one rule: **the campaign has one Hessian-capture accumulator, and the packed capture path feeds the same priced-inputs artifacts #196 writes.**

- `_collect_activations` now has a single inner `accumulate(name, x)` that both the dense `Linear` pre-hook and the packed collector's `row_consumer` call. It tracks the same three per-unit outputs for either population — bounded scoring rows, exact un-normalised XᵀX, and `max|x|` (the input behind #196's static `input_global_scale`). Return is #196's 4-tuple `(rows, hessians, token_counts, max_abs)`; the packed branch no longer has its own row/Hessian bookkeeping. A zero-row call (an expert no token was routed to on a batch) contributes nothing to any of the three.
- Consequently a packed unit *can* feed `_static_input_scales` → `input_scales.safetensors` and `write_export_inputs` → `hessian_capture.pt` by the dense path. Nothing packed reaches those artifacts today: this PR's `_require_campaign_population` (kept in `main()`, before calibration) still refuses a live packed population by name until the #183 cached-wire/stack-plan bridge lands. There is no second notion of "the campaign's Hessian capture".
- Both sides' independent helpers kept: this PR's `_campaign_layer_scope` / `_require_campaign_population` / `profile.is_pinned_name` honouring; #196's `_format_executes_static_nvfp4` / `_require_resumable_anchor` / `write_export_inputs` / served-contract pricing (`static_input_scale=static_scales.get(name)`).
- `docs/ARCHITECTURE.md`: `As of: 2026-09-05 · codex/pq183-packed-capture`; all stamps from both sides kept, newest first (this PR's three above #196's). `e3a2f323` adds one stamp recording the one-capture resolution above.

### Fixes on top of the merge (one commit each)

- `59d17db8` — `tests/test_tessera_scope_endpoints.py::test_campaign_main_passes_live_model_topology_to_real_menu_boundary` failed on this PR's pre-merge tip (`90fdb51c`) as well as after the merge: `prismaquant/tessera_campaign.py:836: AttributeError: 'types.SimpleNamespace' object has no attribute 'named_parameters'`. The population refusal reads `model.named_parameters()`; the stand-in model in that test only offered `named_modules`. Fixture now derives `named_parameters` from its modules. This test had not been run on the branch before.
- `e1c985f3` — `tests/test_tessera_campaign.py::test_the_seam_forwards_the_activation_source_and_nothing_else` fails **in isolation on pristine `main` at the pin** (`tests/test_tessera_campaign.py:775: AssertionError`; passes in whole-file order) — inherited order dependence, not introduced here. Cause: the pinned `encode_linear`'s first call computes `encoder_fixture_id()` by recursing through the (monkeypatched) module-level `encode_linear`, so the second capture overwrote `seen`. The capture now records the first call only. Passes in isolation and in file order.
- `e3a2f323` — ARCHITECTURE.md stamp for the merge decision (docs only).

Post-merge test additions in `tests/test_tessera_campaign_packed.py`: the packed capture test now asserts `max_abs` per packed unit and for the dense sibling, and the subset test asserts the selected unit's `max_abs` is identical to the whole-population run.

### Verification (sparklina, CPU, tessera dev pin `1221d2a`)

```
CUDA_VISIBLE_DEVICES="" PYTHONPATH=/home/rob/tessera-pin-1221d2a/src \
python -m pytest -p no:cacheprovider -q --no-header -n 4 \
  tests/test_tessera_campaign_packed.py tests/test_tessera_campaign_pins.py \
  tests/test_tessera_campaign.py tests/test_tessera_scope_endpoints.py \
  tests/test_architecture_doc.py tests/test_docs_staleness.py \
  tests/test_production_weight_cache.py tests/test_measure_quant_cost_packed_experts.py \
  tests/test_packed_expert_hook_scope.py tests/test_packed_expert_union_identity.py \
  tests/test_routed_expert_namespace_aliasing.py tests/test_model_walk.py \
  tests/test_tessera_export_lane.py tests/test_read_traffic.py tests/test_stock_anchored_cost.py \
  tests/test_streamed_cost_checkpoints.py tests/test_dsv4_layer_streaming_rename.py \
  tests/test_dsv4_nested_rotary_init.py tests/test_glm5_next_streamed_forward_parity.py
→ 288 passed, 7 skipped, 0 failed (tip e3a2f323)
```

(PR's own tests + every test file importing a touched module: `tessera_campaign`, `routed_experts`, `production_weight_cache` + the two doc gates.) Inherited failures from the `main` pin baseline (`test_cluster_campaign_runner.py::test_resume_after_coordinator_death_recovers_owned_helper_receipt`, `test_tessera_export_scope.py::test_selected_export_units_resolve_their_own_structure`) are outside this set and untouched. Full suite not run, per campaign brief.

### Review notes

- Claims vs code hold: `_require_campaign_population` names every in-scope rank-3 packed parameter and refuses (no dense-only payload); `PackedExpertProjection` views use the profile-owned split; `_PackedExpertActivationCollector(row_consumer=…)` runs the consumer before the reservoir, and with `module_token_budget=0`/`store_qnames=set()` it stores nothing; an unobserved selected expert refuses by name; no shared-Hessian or weights-only fallback.
- PR #183 stays open (this PR does not claim the bridge).
